### ISSUE TITLE
Error: Unable to find any expected files for marionette

### ISSUE THREAD

**Issue by blindenvy** [Ardesco/selenium-standalone-server-plugin#36]
Seeing the following error:

```
[ERROR] Failed to execute goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.9:selenium (default) on project foo-selenium: Unable to find any expected files for marionette -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.9:selenium (default) on project foo-selenium: Unable to find any expected files for marionette
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
	at java.lang.reflect.Method.invoke(Method.java:620)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.lazerycode.selenium.exceptions.ExpectedFileNotFoundException: Unable to find any expected files for marionette
	at com.lazerycode.selenium.extract.FileExtractor.unzipFile(FileExtractor.java:96)
	at com.lazerycode.selenium.extract.FileExtractor.extractFileFromArchive(FileExtractor.java:61)
	at com.lazerycode.selenium.download.DownloadHandler.downloadAndExtractExecutableFiles(DownloadHandler.java:127)
	at com.lazerycode.selenium.download.DownloadHandler.ensureStandaloneExecutableFilesExist(DownloadHandler.java:94)
	at com.lazerycode.selenium.SeleniumServerMojo.execute(SeleniumServerMojo.java:240)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
```

This issue is only experienced on windows and not on osx. For more information see https://github.com/Ardesco/Selenium-Maven-Template/issues/21

**Comment by blindenvy** [comment]
I was able to reproduce the issue on my mac by adding the following configuration for the plugin:
```
<onlyGetDriversForHostOperatingSystem>false</onlyGetDriversForHostOperatingSystem>
<operatingSystems>
  <windows>true</windows>
  <linux>true</linux>
  <mac>true</mac>
</operatingSystems>
```

**Comment by blindenvy** [comment]
See pull request #37

**Comment by Ardesco** [comment]
@rultor release, tag is `1.0.10`
