### ISSUE TITLE
version 1.0.13 causes NPE

### ISSUE THREAD

**Issue by SiKing** [Ardesco/selenium-standalone-server-plugin#57]
I am using just the vanilla “default usage” - nothing fancy. Version 1.0.13 running on either Mac or Linux produces NPE:

```
[ERROR] Failed to execute goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.13:selenium (default) on project ldc-integrationtests: Execution default of goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.13:selenium failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.13:selenium (default) on project ldc-integrationtests: Execution default of goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.13:selenium failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.13:selenium failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at sun.misc.MetaIndex.mayContain(MetaIndex.java:242)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1032)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:292)
	at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1264)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.getResource(ClassRealm.java:287)
	at org.codehaus.plexus.resource.loader.ThreadContextClasspathResourceLoader.getResource(ThreadContextClasspathResourceLoader.java:64)
	at org.codehaus.plexus.resource.DefaultResourceManager.getResource(DefaultResourceManager.java:157)
	at org.codehaus.plexus.resource.DefaultResourceManager.getResourceAsFile(DefaultResourceManager.java:81)
	at com.lazerycode.selenium.SeleniumServerMojo.getRepositoryMapFile(SeleniumServerMojo.java:289)
	at com.lazerycode.selenium.SeleniumServerMojo.setRepositoryMapFile(SeleniumServerMojo.java:304)
	at com.lazerycode.selenium.SeleniumServerMojo.execute(SeleniumServerMojo.java:205)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

**Comment by Ardesco** [comment]
@rultor release, tag is `1.0.14`
